# Generated by Django 4.0.5 on 2022-06-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLeccion', models.CharField(max_length=200)),
                ('documentacion', models.TextField()),
                ('respuestaCorrecta', models.CharField(max_length=200)),
                ('respuesIncorrecta1', models.CharField(max_length=200)),
                ('respuesIncorrecta2', models.CharField(max_length=200)),
                ('respuesIncorrecta3', models.CharField(max_length=200)),
                ('puntaje', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PuntosPorJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajeAnual', models.IntegerField(default=0)),
                ('puntajeTotal', models.IntegerField(default=0)),
                ('idJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
