# Generated by Django 4.0.5 on 2022-06-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeMastersApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentacion',
            old_name='respuesIncorrecta1',
            new_name='respuestaIncorrecta1',
        ),
        migrations.RenameField(
            model_name='documentacion',
            old_name='respuesIncorrecta2',
            new_name='respuestaIncorrecta2',
        ),
        migrations.RenameField(
            model_name='documentacion',
            old_name='respuesIncorrecta3',
            new_name='respuestaIncorrecta3',
        ),
    ]
