# Generated by Django 4.0.5 on 2022-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeMastersApi', '0002_rename_respuesincorrecta1_documentacion_respuestaincorrecta1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='preguntaQuizz',
            field=models.CharField(default='Hola', max_length=200),
        ),
    ]
