# Generated by Django 4.0.5 on 2022-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeMastersApi', '0003_documentacion_preguntaquizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosporjugador',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
