# Generated by Django 4.0.5 on 2022-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeMastersApi', '0004_puntosporjugador_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='preguntaQuizz',
            field=models.CharField(max_length=200),
        ),
    ]
