# Generated by Django 4.0.5 on 2022-06-29 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeMastersApi', '0006_hechoporjugador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HechoPorJugador',
            new_name='DocumentacionHechoPorJugador',
        ),
    ]
